name: jcrm_ui_flutter
description: Flutter implementation of UI for jCRM

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  collection: ^1.18.0
  path_to_regexp: ^0.4.0
  quiver: ^3.2.1
  url_launcher: ^6.2.1
  intl: ^0.20.1
  web: ^1.1.0

  adaptive_navigation: ^0.0.10
  url_strategy: ^0.3.0

  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
